baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Cytoscape Workflow Collection"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Cytoscape Consortium"
	description = "Cytoscape Workflows written in various programming languages."
	copyright = "CC BY 4.0"

	# Repository
	provider = "GitHub"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "light-green"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = "cytoscape"
	github  = "cytoscape"


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
